FROM node:13.8.0-alpine3.11

COPY package.json package-lock.json ./
RUN npm ci

COPY ./index.js ./index.js

ARG ENV
ARG REDIS_HOST
ARG NASA_API_KEY
ARG BOT_SECRET_TOKEN

ENV ENV=$ENV
ENV REDIS_HOST=$REDIS_HOST
ENV NASA_API_KEY=$NASA_API_KEY
ENV BOT_SECRET_TOKEN=$BOT_SECRET_TOKEN

CMD ["node", "index.js"]